// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hermes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // optional conversation thread
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                          // e.g. "opencode/oc-deepseek-v4-flash-free"
	History       []*ChatMessage         `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`                      // prior conversation context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_hermes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant" | "system"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_hermes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	TokensUsed    int64                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_hermes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *ChatResponse) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ChatResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type ChatStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_hermes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamChunk.ProtoReflect.Descriptor instead.
func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatStreamChunk) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_hermes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{4}
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Relevance     float64                `protobuf:"fixed64,2,opt,name=relevance,proto3" json:"relevance,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResult) Reset() {
	*x = RecallResult{}
	mi := &file_hermes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResult) ProtoMessage() {}

func (x *RecallResult) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResult.ProtoReflect.Descriptor instead.
func (*RecallResult) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{5}
}

func (x *RecallResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RecallResult) GetRelevance() float64 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

func (x *RecallResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RecallResult) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RecallResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_hermes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{6}
}

func (x *RecallResponse) GetResults() []*RecallResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RetainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainRequest) Reset() {
	*x = RetainRequest{}
	mi := &file_hermes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainRequest) ProtoMessage() {}

func (x *RetainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainRequest.ProtoReflect.Descriptor instead.
func (*RetainRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{7}
}

func (x *RetainRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetainRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *RetainRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RetainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainResponse) Reset() {
	*x = RetainResponse{}
	mi := &file_hermes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainResponse) ProtoMessage() {}

func (x *RetainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainResponse.ProtoReflect.Descriptor instead.
func (*RetainResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{8}
}

func (x *RetainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetainResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReflectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectRequest) Reset() {
	*x = ReflectRequest{}
	mi := &file_hermes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectRequest) ProtoMessage() {}

func (x *ReflectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectRequest.ProtoReflect.Descriptor instead.
func (*ReflectRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{9}
}

func (x *ReflectRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ReflectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synthesis     string                 `protobuf:"bytes,1,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectResponse) Reset() {
	*x = ReflectResponse{}
	mi := &file_hermes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectResponse) ProtoMessage() {}

func (x *ReflectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectResponse.ProtoReflect.Descriptor instead.
func (*ReflectResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{10}
}

func (x *ReflectResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

func (x *ReflectResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_hermes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{11}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CpuInfo               `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryInfo            `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       *StorageInfo           `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Kernel        string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_hermes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetCpu() *CpuInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *StatusResponse) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *StatusResponse) GetStorage() *StorageInfo {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatusResponse) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type CpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Governor      string                 `protobuf:"bytes,3,opt,name=governor,proto3" json:"governor,omitempty"`
	Load_1M       float64                `protobuf:"fixed64,4,opt,name=load_1m,json=load1m,proto3" json:"load_1m,omitempty"`
	Load_5M       float64                `protobuf:"fixed64,5,opt,name=load_5m,json=load5m,proto3" json:"load_5m,omitempty"`
	Load_15M      float64                `protobuf:"fixed64,6,opt,name=load_15m,json=load15m,proto3" json:"load_15m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuInfo) Reset() {
	*x = CpuInfo{}
	mi := &file_hermes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfo) ProtoMessage() {}

func (x *CpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfo.ProtoReflect.Descriptor instead.
func (*CpuInfo) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{13}
}

func (x *CpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CpuInfo) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CpuInfo) GetGovernor() string {
	if x != nil {
		return x.Governor
	}
	return ""
}

func (x *CpuInfo) GetLoad_1M() float64 {
	if x != nil {
		return x.Load_1M
	}
	return 0
}

func (x *CpuInfo) GetLoad_5M() float64 {
	if x != nil {
		return x.Load_5M
	}
	return 0
}

func (x *CpuInfo) GetLoad_15M() float64 {
	if x != nil {
		return x.Load_15M
	}
	return 0
}

type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKb       int64                  `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"`
	FreeKb        int64                  `protobuf:"varint,2,opt,name=free_kb,json=freeKb,proto3" json:"free_kb,omitempty"`
	AvailableKb   int64                  `protobuf:"varint,3,opt,name=available_kb,json=availableKb,proto3" json:"available_kb,omitempty"`
	SwapTotalKb   int64                  `protobuf:"varint,4,opt,name=swap_total_kb,json=swapTotalKb,proto3" json:"swap_total_kb,omitempty"`
	SwapUsedKb    int64                  `protobuf:"varint,5,opt,name=swap_used_kb,json=swapUsedKb,proto3" json:"swap_used_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_hermes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{14}
}

func (x *MemoryInfo) GetTotalKb() int64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

func (x *MemoryInfo) GetFreeKb() int64 {
	if x != nil {
		return x.FreeKb
	}
	return 0
}

func (x *MemoryInfo) GetAvailableKb() int64 {
	if x != nil {
		return x.AvailableKb
	}
	return 0
}

func (x *MemoryInfo) GetSwapTotalKb() int64 {
	if x != nil {
		return x.SwapTotalKb
	}
	return 0
}

func (x *MemoryInfo) GetSwapUsedKb() int64 {
	if x != nil {
		return x.SwapUsedKb
	}
	return 0
}

type StorageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,2,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	Mount         string                 `protobuf:"bytes,3,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageInfo) Reset() {
	*x = StorageInfo{}
	mi := &file_hermes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageInfo) ProtoMessage() {}

func (x *StorageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageInfo.ProtoReflect.Descriptor instead.
func (*StorageInfo) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{15}
}

func (x *StorageInfo) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageInfo) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *StorageInfo) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

type ServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesRequest) Reset() {
	*x = ServicesRequest{}
	mi := &file_hermes_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesRequest) ProtoMessage() {}

func (x *ServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesRequest.ProtoReflect.Descriptor instead.
func (*ServicesRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{16}
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running" | "stopped" | "error"
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_hermes_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ServiceInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	mi := &file_hermes_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{18}
}

func (x *ServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Workdir       string                 `protobuf:"bytes,2,opt,name=workdir,proto3" json:"workdir,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,3,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	Background    bool                   `protobuf:"varint,4,opt,name=background,proto3" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_hermes_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *ExecuteRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_hermes_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecuteResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecuteChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ExecuteChunk_StdoutLine
	//	*ExecuteChunk_StderrLine
	Data          isExecuteChunk_Data `protobuf_oneof:"data"`
	Done          bool                `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32               `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteChunk) Reset() {
	*x = ExecuteChunk{}
	mi := &file_hermes_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteChunk) ProtoMessage() {}

func (x *ExecuteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteChunk.ProtoReflect.Descriptor instead.
func (*ExecuteChunk) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteChunk) GetData() isExecuteChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteChunk) GetStdoutLine() string {
	if x != nil {
		if x, ok := x.Data.(*ExecuteChunk_StdoutLine); ok {
			return x.StdoutLine
		}
	}
	return ""
}

func (x *ExecuteChunk) GetStderrLine() string {
	if x != nil {
		if x, ok := x.Data.(*ExecuteChunk_StderrLine); ok {
			return x.StderrLine
		}
	}
	return ""
}

func (x *ExecuteChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecuteChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type isExecuteChunk_Data interface {
	isExecuteChunk_Data()
}

type ExecuteChunk_StdoutLine struct {
	StdoutLine string `protobuf:"bytes,1,opt,name=stdout_line,json=stdoutLine,proto3,oneof"`
}

type ExecuteChunk_StderrLine struct {
	StderrLine string `protobuf:"bytes,2,opt,name=stderr_line,json=stderrLine,proto3,oneof"`
}

func (*ExecuteChunk_StdoutLine) isExecuteChunk_Data() {}

func (*ExecuteChunk_StderrLine) isExecuteChunk_Data() {}

var File_hermes_proto protoreflect.FileDescriptor

const file_hermes_proto_rawDesc = "" +
	"\n" +
	"\fhermes.proto\x12\x06hermes\"\x8b\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12-\n" +
	"\ahistory\x18\x04 \x03(\v2\x13.hermes.ChatMessageR\ahistory\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x83\x01\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x03R\n" +
	"tokensUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\"^\n" +
	"\x0fChatStreamChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\";\n" +
	"\rRecallRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"x\n" +
	"\fRecallResult\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\trelevance\x18\x02 \x01(\x01R\trelevance\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"@\n" +
	"\x0eRecallResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.hermes.RecallResultR\aresults\"W\n" +
	"\rRetainRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\":\n" +
	"\x0eRetainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"&\n" +
	"\x0eReflectRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"I\n" +
	"\x0fReflectResponse\x12\x1c\n" +
	"\tsynthesis\x18\x01 \x01(\tR\tsynthesis\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"\x0f\n" +
	"\rStatusRequest\"\xbe\x01\n" +
	"\x0eStatusResponse\x12!\n" +
	"\x03cpu\x18\x01 \x01(\v2\x0f.hermes.CpuInfoR\x03cpu\x12*\n" +
	"\x06memory\x18\x02 \x01(\v2\x12.hermes.MemoryInfoR\x06memory\x12-\n" +
	"\astorage\x18\x03 \x01(\v2\x13.hermes.StorageInfoR\astorage\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\"\x9e\x01\n" +
	"\aCpuInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x1a\n" +
	"\bgovernor\x18\x03 \x01(\tR\bgovernor\x12\x17\n" +
	"\aload_1m\x18\x04 \x01(\x01R\x06load1m\x12\x17\n" +
	"\aload_5m\x18\x05 \x01(\x01R\x06load5m\x12\x19\n" +
	"\bload_15m\x18\x06 \x01(\x01R\aload15m\"\xa9\x01\n" +
	"\n" +
	"MemoryInfo\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x03R\atotalKb\x12\x17\n" +
	"\afree_kb\x18\x02 \x01(\x03R\x06freeKb\x12!\n" +
	"\favailable_kb\x18\x03 \x01(\x03R\vavailableKb\x12\"\n" +
	"\rswap_total_kb\x18\x04 \x01(\x03R\vswapTotalKb\x12 \n" +
	"\fswap_used_kb\x18\x05 \x01(\x03R\n" +
	"swapUsedKb\"c\n" +
	"\vStorageInfo\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x02 \x01(\x03R\tfreeBytes\x12\x14\n" +
	"\x05mount\x18\x03 \x01(\tR\x05mount\"\x11\n" +
	"\x0fServicesRequest\"g\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\"C\n" +
	"\x10ServicesResponse\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.hermes.ServiceInfoR\bservices\"\x85\x01\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\aworkdir\x18\x02 \x01(\tR\aworkdir\x12\x1f\n" +
	"\vtimeout_sec\x18\x03 \x01(\x05R\n" +
	"timeoutSec\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\bR\n" +
	"background\"\x91\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x01R\n" +
	"durationMs\"\x8d\x01\n" +
	"\fExecuteChunk\x12!\n" +
	"\vstdout_line\x18\x01 \x01(\tH\x00R\n" +
	"stdoutLine\x12!\n" +
	"\vstderr_line\x18\x02 \x01(\tH\x00R\n" +
	"stderrLine\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCodeB\x06\n" +
	"\x04data2~\n" +
	"\vChatService\x121\n" +
	"\x04Chat\x12\x13.hermes.ChatRequest\x1a\x14.hermes.ChatResponse\x12<\n" +
	"\n" +
	"ChatStream\x12\x13.hermes.ChatRequest\x1a\x17.hermes.ChatStreamChunk0\x012\xbd\x01\n" +
	"\rMemoryService\x127\n" +
	"\x06Recall\x12\x15.hermes.RecallRequest\x1a\x16.hermes.RecallResponse\x127\n" +
	"\x06Retain\x12\x15.hermes.RetainRequest\x1a\x16.hermes.RetainResponse\x12:\n" +
	"\aReflect\x12\x16.hermes.ReflectRequest\x1a\x17.hermes.ReflectResponse2\x8d\x01\n" +
	"\rSystemService\x12:\n" +
	"\tGetStatus\x12\x15.hermes.StatusRequest\x1a\x16.hermes.StatusResponse\x12@\n" +
	"\vGetServices\x12\x17.hermes.ServicesRequest\x1a\x18.hermes.ServicesResponse2\x8e\x01\n" +
	"\x0fTerminalService\x12:\n" +
	"\aExecute\x12\x16.hermes.ExecuteRequest\x1a\x17.hermes.ExecuteResponse\x12?\n" +
	"\rExecuteStream\x12\x16.hermes.ExecuteRequest\x1a\x14.hermes.ExecuteChunk0\x01B7Z5github.com/prince/hermes-backend/internal/api/grpc/pbb\x06proto3"

var (
	file_hermes_proto_rawDescOnce sync.Once
	file_hermes_proto_rawDescData []byte
)

func file_hermes_proto_rawDescGZIP() []byte {
	file_hermes_proto_rawDescOnce.Do(func() {
		file_hermes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hermes_proto_rawDesc), len(file_hermes_proto_rawDesc)))
	})
	return file_hermes_proto_rawDescData
}

var file_hermes_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_hermes_proto_goTypes = []any{
	(*ChatRequest)(nil),      // 0: hermes.ChatRequest
	(*ChatMessage)(nil),      // 1: hermes.ChatMessage
	(*ChatResponse)(nil),     // 2: hermes.ChatResponse
	(*ChatStreamChunk)(nil),  // 3: hermes.ChatStreamChunk
	(*RecallRequest)(nil),    // 4: hermes.RecallRequest
	(*RecallResult)(nil),     // 5: hermes.RecallResult
	(*RecallResponse)(nil),   // 6: hermes.RecallResponse
	(*RetainRequest)(nil),    // 7: hermes.RetainRequest
	(*RetainResponse)(nil),   // 8: hermes.RetainResponse
	(*ReflectRequest)(nil),   // 9: hermes.ReflectRequest
	(*ReflectResponse)(nil),  // 10: hermes.ReflectResponse
	(*StatusRequest)(nil),    // 11: hermes.StatusRequest
	(*StatusResponse)(nil),   // 12: hermes.StatusResponse
	(*CpuInfo)(nil),          // 13: hermes.CpuInfo
	(*MemoryInfo)(nil),       // 14: hermes.MemoryInfo
	(*StorageInfo)(nil),      // 15: hermes.StorageInfo
	(*ServicesRequest)(nil),  // 16: hermes.ServicesRequest
	(*ServiceInfo)(nil),      // 17: hermes.ServiceInfo
	(*ServicesResponse)(nil), // 18: hermes.ServicesResponse
	(*ExecuteRequest)(nil),   // 19: hermes.ExecuteRequest
	(*ExecuteResponse)(nil),  // 20: hermes.ExecuteResponse
	(*ExecuteChunk)(nil),     // 21: hermes.ExecuteChunk
}
var file_hermes_proto_depIdxs = []int32{
	1,  // 0: hermes.ChatRequest.history:type_name -> hermes.ChatMessage
	5,  // 1: hermes.RecallResponse.results:type_name -> hermes.RecallResult
	13, // 2: hermes.StatusResponse.cpu:type_name -> hermes.CpuInfo
	14, // 3: hermes.StatusResponse.memory:type_name -> hermes.MemoryInfo
	15, // 4: hermes.StatusResponse.storage:type_name -> hermes.StorageInfo
	17, // 5: hermes.ServicesResponse.services:type_name -> hermes.ServiceInfo
	0,  // 6: hermes.ChatService.Chat:input_type -> hermes.ChatRequest
	0,  // 7: hermes.ChatService.ChatStream:input_type -> hermes.ChatRequest
	4,  // 8: hermes.MemoryService.Recall:input_type -> hermes.RecallRequest
	7,  // 9: hermes.MemoryService.Retain:input_type -> hermes.RetainRequest
	9,  // 10: hermes.MemoryService.Reflect:input_type -> hermes.ReflectRequest
	11, // 11: hermes.SystemService.GetStatus:input_type -> hermes.StatusRequest
	16, // 12: hermes.SystemService.GetServices:input_type -> hermes.ServicesRequest
	19, // 13: hermes.TerminalService.Execute:input_type -> hermes.ExecuteRequest
	19, // 14: hermes.TerminalService.ExecuteStream:input_type -> hermes.ExecuteRequest
	2,  // 15: hermes.ChatService.Chat:output_type -> hermes.ChatResponse
	3,  // 16: hermes.ChatService.ChatStream:output_type -> hermes.ChatStreamChunk
	6,  // 17: hermes.MemoryService.Recall:output_type -> hermes.RecallResponse
	8,  // 18: hermes.MemoryService.Retain:output_type -> hermes.RetainResponse
	10, // 19: hermes.MemoryService.Reflect:output_type -> hermes.ReflectResponse
	12, // 20: hermes.SystemService.GetStatus:output_type -> hermes.StatusResponse
	18, // 21: hermes.SystemService.GetServices:output_type -> hermes.ServicesResponse
	20, // 22: hermes.TerminalService.Execute:output_type -> hermes.ExecuteResponse
	21, // 23: hermes.TerminalService.ExecuteStream:output_type -> hermes.ExecuteChunk
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_hermes_proto_init() }
func file_hermes_proto_init() {
	if File_hermes_proto != nil {
		return
	}
	file_hermes_proto_msgTypes[21].OneofWrappers = []any{
		(*ExecuteChunk_StdoutLine)(nil),
		(*ExecuteChunk_StderrLine)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hermes_proto_rawDesc), len(file_hermes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_hermes_proto_goTypes,
		DependencyIndexes: file_hermes_proto_depIdxs,
		MessageInfos:      file_hermes_proto_msgTypes,
	}.Build()
	File_hermes_proto = out.File
	file_hermes_proto_goTypes = nil
	file_hermes_proto_depIdxs = nil
}
